name: Check Standard Updates Every 30 Minutes

permissions:
  contents: write
  pull-requests: write

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  check-standard-updates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Run watcher script and save results
        env:
          SAVE_RESULTS: "1"
        run: node watcher.js
      - name: Create Pull Request for results
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "chore: update standard check results [skip ci]"
          title: "Update standard check results"
          body: |
            自动更新标准检查结果。
            合并后 `check-results.md` 文件会包含最新检测结果。
          branch: "auto/update-standard-results"
          add-paths: check-results.md