name: Check Standard Updates Every 30 Minutes

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run script
        run: node watcher.js

      - name: Commit and push updates.md if changed
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add updates.md
          git diff --cached --quiet || git commit -m "chore: update standards status [skip ci]"
          git push